name: AppName
targets:
  AppName:
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    sources:
      - Sources
      - path: jbdev.plist
        buildPhase: resources
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.AppName
        CODE_SIGNING_ALLOWED: "NO"
        CODE_SIGN_REQUIRED: "NO"
        CODE_SIGN_IDENTITY: ""
        PROVISIONING_PROFILE_SPECIFIER: ""
        CODE_SIGN_ENTITLEMENTS: AppName.ent
    postBuildScripts:
      - script: bash jbdev.build.sh
        name: JBDev Build Script

